### ISSUE TITLE
would you make implementation of Ranked List Loss 

### ISSUE THREAD

**Issue by DogeWatch** [KevinMusgrave/pytorch-metric-learning#285] opened 2021-03-02 09:10 UTC
paper name is : Ranked List Loss for Deep Metric Learning
here is the paper: https://arxiv.org/pdf/1903.03238.pdf

**Comment by KevinMusgrave** [comment] 2021-03-02 12:42
I might do this sometime in the future, but I'm unlikely to do it anytime soon

**Comment by KevinMusgrave** [comment] 2021-03-03 23:11
Closing because this is a duplicate of #191

**Closed by KevinMusgrave** 2021-03-03 23:11 UTC
Labels: new algorithm request
