### ISSUE TITLE
RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements

### ISSUE THREAD

**Issue by PuNeal** [KevinMusgrave/pytorch-metric-learning#367] opened 2021-09-23 07:44 UTC
hello, I met a problem when I trained model with triplet-margin loss, the error message as follows:
```
 File "/home/bengui/miniconda3/envs/torch1.7/lib/python3.6/site-packages/pytorch_metric_learning-0.9.99-py3.6.egg/pytorch_metric_learning/losses/base_metric_loss_function.py", line 34, in forward
  File "/home/bengui/miniconda3/envs/torch1.7/lib/python3.6/site-packages/pytorch_metric_learning-0.9.99-py3.6.egg/pytorch_metric_learning/losses/triplet_margin_loss.py", line 35, in compute_loss
  File "/home/bengui/miniconda3/envs/torch1.7/lib/python3.6/site-packages/pytorch_metric_learning-0.9.99-py3.6.egg/pytorch_metric_learning/utils/loss_and_miner_utils.py", line 195, in convert_to_triplets
RuntimeError: nonzero is not supported for tensors with more than INT_MAX elements,   file a support request
```
I found this error happened in the function: convert_to_triplets. The batchsize is 600 and images per class is 200. Could you help me fix this error? Thanks a lot.

**Comment by KevinMusgrave** [comment] 2021-09-23 12:58
Can you try a smaller batch size? I'm not sure what the cause is, but I found some related discussions: 

https://discuss.pytorch.org/t/torch-geometric/106975
https://github.com/pytorch/pytorch/issues/51871

**Comment by PuNeal** [comment] 2021-09-26 09:47
Yes, it works with batchsize=400

**Comment by KevinMusgrave** [comment] 2021-09-26 21:22
Ok, it seems like a batch size issue then. I'll close this for now. Please comment if you get this error again.

**Comment by KevinMusgrave** [comment] 2022-07-21 20:36
Good idea, I'll add a note to the documentation

**Closed** 2022-08-03 18:51 UTC
Labels: documentation, question
