### ISSUE TITLE
RuntimeError: Integer division of tensors using div or / is no longer supported

### ISSUE THREAD

**Issue by VladKatsman** [KevinMusgrave/pytorch-metric-learning#499] opened 2022-07-18 09:55 UTC
file: **loss_and_miner_utils.py**

line: **209**
**counts = c_f.to_dtype(counts, dtype=dtype) / torch.sum(counts)**

returns error:
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.

**Comment by KevinMusgrave** [comment] 2022-07-18 20:33
When does this happen? With a particular loss function?

**Comment by VladKatsman** [comment] 2022-07-21 13:48
I use arcfaceloss with subcenters, mean reducer (default) and no mining

**Comment by KevinMusgrave** [comment] 2022-07-21 21:14
I'm not able to reproduce. 

What version of pytorch and pytorch_metric_learning are you using?

Which miner are you using?

Are you running or CPU or GPU?

**Comment by KevinMusgrave** [comment] 2022-07-29 11:27
Closing for now

**Closed by KevinMusgrave** 2022-07-29 11:27 UTC
Labels: possible bug?
